version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tamo
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
